// 深圳小学英语单词库
// 基于上海教育出版社（沪教版）教材
// 适用于深圳小学 1-6 年级
// 说明：
// 1. 1-1 到 2-2 暂保留项目原有词库；
// 2. 3-1 到 6-2 已于 2026-03-29 按用户提供的沪教版词表补齐；
// 3. 对源表中的少量明显录入错误做了纠正，例如 tall、bus driver、keep quiet、fairy tale。

const WORD_DATA = {
    "1-1": [
        { word: "hello", meaning: "你好", category: "greeting" },
        { word: "hi", meaning: "你好", category: "greeting" },
        { word: "goodbye", meaning: "再见", category: "greeting" },
        { word: "bye", meaning: "再见", category: "greeting" },
        { word: "I", meaning: "我", category: "pronoun" },
        { word: "am", meaning: "是", category: "verb" },
        { word: "I'm", meaning: "我是", category: "phrase" },
        { word: "good", meaning: "好的", category: "adj" },
        { word: "morning", meaning: "早晨", category: "time" },
        { word: "good morning", meaning: "早上好", category: "greeting" },
        { word: "afternoon", meaning: "下午", category: "time" },
        { word: "good afternoon", meaning: "下午好", category: "greeting" },
        { word: "evening", meaning: "傍晚", category: "time" },
        { word: "good evening", meaning: "晚上好", category: "greeting" },
        { word: "night", meaning: "夜晚", category: "time" },
        { word: "good night", meaning: "晚安", category: "greeting" },
        { word: "how", meaning: "怎样", category: "question" },
        { word: "are", meaning: "是", category: "verb" },
        { word: "you", meaning: "你", category: "pronoun" },
        { word: "how are you", meaning: "你好吗", category: "phrase" },
        { word: "thank", meaning: "感谢", category: "verb" },
        { word: "thanks", meaning: "谢谢", category: "phrase" },
        { word: "thank you", meaning: "谢谢你", category: "phrase" },
        { word: "welcome", meaning: "不客气", category: "phrase" },
        { word: "sorry", meaning: "对不起", category: "phrase" },
        { word: "OK", meaning: "好的", category: "phrase" },
        { word: "what", meaning: "什么", category: "question" },
        { word: "name", meaning: "名字", category: "noun" },
        { word: "your", meaning: "你的", category: "pronoun" },
        { word: "what's your name", meaning: "你叫什么名字", category: "phrase" },
        { word: "my", meaning: "我的", category: "pronoun" },
        { word: "nice", meaning: "美好的", category: "adj" },
        { word: "to", meaning: "向", category: "prep" },
        { word: "meet", meaning: "遇见", category: "verb" },
        { word: "nice to meet you", meaning: "很高兴认识你", category: "phrase" },
        { word: "red", meaning: "红色", category: "color" },
        { word: "blue", meaning: "蓝色", category: "color" },
        { word: "yellow", meaning: "黄色", category: "color" },
        { word: "green", meaning: "绿色", category: "color" },
        { word: "one", meaning: "一", category: "number" },
        { word: "two", meaning: "二", category: "number" },
        { word: "three", meaning: "三", category: "number" },
        { word: "four", meaning: "四", category: "number" },
        { word: "five", meaning: "五", category: "number" }
    ],

    "1-2": [
        { word: "orange", meaning: "橙色", category: "color" },
        { word: "purple", meaning: "紫色", category: "color" },
        { word: "pink", meaning: "粉色", category: "color" },
        { word: "brown", meaning: "棕色", category: "color" },
        { word: "black", meaning: "黑色", category: "color" },
        { word: "white", meaning: "白色", category: "color" },
        { word: "six", meaning: "六", category: "number" },
        { word: "seven", meaning: "七", category: "number" },
        { word: "eight", meaning: "八", category: "number" },
        { word: "nine", meaning: "九", category: "number" },
        { word: "ten", meaning: "十", category: "number" },
        { word: "cat", meaning: "猫", category: "animal" },
        { word: "dog", meaning: "狗", category: "animal" },
        { word: "bird", meaning: "鸟", category: "animal" },
        { word: "fish", meaning: "鱼", category: "animal" },
        { word: "duck", meaning: "鸭子", category: "animal" },
        { word: "eye", meaning: "眼睛", category: "body" },
        { word: "nose", meaning: "鼻子", category: "body" },
        { word: "mouth", meaning: "嘴巴", category: "body" },
        { word: "face", meaning: "脸", category: "body" },
        { word: "head", meaning: "头", category: "body" },
        { word: "hand", meaning: "手", category: "body" },
        { word: "leg", meaning: "腿", category: "body" },
        { word: "foot", meaning: "脚", category: "body" },
        { word: "mother", meaning: "妈妈", category: "family" },
        { word: "father", meaning: "爸爸", category: "family" },
        { word: "mum", meaning: "妈妈", category: "family" },
        { word: "dad", meaning: "爸爸", category: "family" }
    ],

    "2-1": [
        { word: "rabbit", meaning: "兔子", category: "animal" },
        { word: "bear", meaning: "熊", category: "animal" },
        { word: "pig", meaning: "猪", category: "animal" },
        { word: "monkey", meaning: "猴子", category: "animal" },
        { word: "elephant", meaning: "大象", category: "animal" },
        { word: "apple", meaning: "苹果", category: "food" },
        { word: "banana", meaning: "香蕉", category: "food" },
        { word: "bread", meaning: "面包", category: "food" },
        { word: "milk", meaning: "牛奶", category: "drink" },
        { word: "water", meaning: "水", category: "drink" },
        { word: "egg", meaning: "鸡蛋", category: "food" },
        { word: "rice", meaning: "米饭", category: "food" },
        { word: "book", meaning: "书", category: "school" },
        { word: "pen", meaning: "钢笔", category: "school" },
        { word: "pencil", meaning: "铅笔", category: "school" },
        { word: "ruler", meaning: "尺子", category: "school" },
        { word: "eraser", meaning: "橡皮", category: "school" },
        { word: "bag", meaning: "书包", category: "school" },
        { word: "school", meaning: "学校", category: "place" },
        { word: "classroom", meaning: "教室", category: "place" },
        { word: "desk", meaning: "课桌", category: "school" },
        { word: "chair", meaning: "椅子", category: "school" },
        { word: "teacher", meaning: "老师", category: "person" },
        { word: "student", meaning: "学生", category: "person" }
    ],

    "2-2": [
        { word: "cake", meaning: "蛋糕", category: "food" },
        { word: "chicken", meaning: "鸡肉", category: "food" },
        { word: "juice", meaning: "果汁", category: "drink" },
        { word: "home", meaning: "家", category: "place" },
        { word: "park", meaning: "公园", category: "place" },
        { word: "zoo", meaning: "动物园", category: "place" },
        { word: "library", meaning: "图书馆", category: "place" },
        { word: "Sunday", meaning: "星期日", category: "day" },
        { word: "Monday", meaning: "星期一", category: "day" },
        { word: "Tuesday", meaning: "星期二", category: "day" },
        { word: "Wednesday", meaning: "星期三", category: "day" },
        { word: "Thursday", meaning: "星期四", category: "day" },
        { word: "Friday", meaning: "星期五", category: "day" },
        { word: "Saturday", meaning: "星期六", category: "day" },
        { word: "sunny", meaning: "晴朗的", category: "weather" },
        { word: "rainy", meaning: "下雨的", category: "weather" },
        { word: "cloudy", meaning: "多云的", category: "weather" },
        { word: "windy", meaning: "刮风的", category: "weather" },
        { word: "run", meaning: "跑", category: "verb" },
        { word: "jump", meaning: "跳", category: "verb" },
        { word: "walk", meaning: "走", category: "verb" },
        { word: "sit", meaning: "坐", category: "verb" },
        { word: "stand", meaning: "站", category: "verb" }
    ],

    "3-1": [
        { word: "hello", meaning: "你好", category: "greeting" },
        { word: "morning", meaning: "早晨，上午", category: "time" },
        { word: "Miss", meaning: "小姐", category: "title" },
        { word: "I", meaning: "我", category: "pronoun" },
        { word: "good", meaning: "好的", category: "adj" },
        { word: "Mr", meaning: "先生", category: "title" },
        { word: "Mrs", meaning: "太太", category: "title" },
        { word: "are", meaning: "是", category: "verb" },
        { word: "fine", meaning: "健康的", category: "adj" },
        { word: "goodbye", meaning: "再见", category: "greeting" },
        { word: "hi", meaning: "嗨", category: "greeting" },
        { word: "thank", meaning: "谢谢", category: "verb" },
        { word: "you", meaning: "你，你们", category: "pronoun" },
        { word: "boy", meaning: "男孩", category: "person" },
        { word: "girl", meaning: "女孩", category: "person" },
        { word: "am", meaning: "是", category: "verb" },
        { word: "no", meaning: "不，不是", category: "adv" },
        { word: "not", meaning: "不是", category: "adv" },
        { word: "yes", meaning: "是", category: "adv" },
        { word: "tall", meaning: "高的", category: "adj" },
        { word: "short", meaning: "矮的", category: "adj" },
        { word: "fat", meaning: "胖的", category: "adj" },
        { word: "thin", meaning: "瘦的", category: "adj" },
        { word: "friend", meaning: "朋友", category: "person" },
        { word: "is", meaning: "是", category: "verb" },
        { word: "he", meaning: "他", category: "pronoun" },
        { word: "my", meaning: "我的", category: "pronoun" },
        { word: "this", meaning: "这，这个", category: "pronoun" },
        { word: "she", meaning: "她", category: "pronoun" },
        { word: "father", meaning: "爸爸", category: "family" },
        { word: "mother", meaning: "妈妈", category: "family" },
        { word: "brother", meaning: "哥哥，弟弟", category: "family" },
        { word: "sister", meaning: "姐姐，妹妹", category: "family" },
        { word: "me", meaning: "我", category: "pronoun" },
        { word: "beautiful", meaning: "美丽的", category: "adj" },
        { word: "who", meaning: "谁", category: "question" },
        { word: "family", meaning: "家庭", category: "noun" },
        { word: "hair", meaning: "头发", category: "body" },
        { word: "eye", meaning: "眼睛", category: "body" },
        { word: "ear", meaning: "耳朵", category: "body" },
        { word: "nose", meaning: "鼻子", category: "body" },
        { word: "mouth", meaning: "嘴巴", category: "body" },
        { word: "face", meaning: "脸", category: "body" },
        { word: "big", meaning: "大的", category: "adj" },
        { word: "long", meaning: "长的", category: "adj" },
        { word: "look", meaning: "看", category: "verb" },
        { word: "small", meaning: "小的", category: "adj" },
        { word: "blackboard", meaning: "黑板", category: "school" },
        { word: "door", meaning: "门", category: "furniture" },
        { word: "window", meaning: "窗户", category: "furniture" },
        { word: "clean", meaning: "把……擦干净，打扫", category: "verb" },
        { word: "please", meaning: "请", category: "phrase" },
        { word: "late", meaning: "迟到", category: "adj" },
        { word: "look at", meaning: "看", category: "phrase" },
        { word: "open", meaning: "打开", category: "verb" },
        { word: "close", meaning: "关", category: "verb" },
        { word: "the", meaning: "这个，那些", category: "article" },
        { word: "a", meaning: "一个", category: "article" },
        { word: "an", meaning: "一个", category: "article" },
        { word: "apple", meaning: "苹果", category: "food" },
        { word: "banana", meaning: "香蕉", category: "food" },
        { word: "orange", meaning: "橘子", category: "food" },
        { word: "pear", meaning: "梨", category: "food" },
        { word: "dad", meaning: "爸爸", category: "family" },
        { word: "here", meaning: "这里", category: "place" },
        { word: "how much", meaning: "多少（询问价钱）", category: "phrase" },
        { word: "they", meaning: "他们，她们，它们", category: "pronoun" },
        { word: "it", meaning: "它", category: "pronoun" },
        { word: "chair", meaning: "椅子", category: "furniture" },
        { word: "desk", meaning: "书桌", category: "school" },
        { word: "pen", meaning: "钢笔", category: "school" },
        { word: "bed", meaning: "床", category: "furniture" },
        { word: "schoolbag", meaning: "书包", category: "school" },
        { word: "book", meaning: "书", category: "school" },
        { word: "these", meaning: "这些", category: "pronoun" },
        { word: "pencil", meaning: "铅笔", category: "school" },
        { word: "ruler", meaning: "尺子", category: "school" },
        { word: "mum", meaning: "妈妈", category: "family" },
        { word: "your", meaning: "你的，你们的", category: "pronoun" },
        { word: "one", meaning: "一", category: "number" },
        { word: "two", meaning: "二", category: "number" },
        { word: "three", meaning: "三", category: "number" },
        { word: "four", meaning: "四", category: "number" },
        { word: "five", meaning: "五", category: "number" },
        { word: "six", meaning: "六", category: "number" },
        { word: "seven", meaning: "七", category: "number" },
        { word: "eight", meaning: "八", category: "number" },
        { word: "nine", meaning: "九", category: "number" },
        { word: "ten", meaning: "十", category: "number" },
        { word: "how many", meaning: "多少（询问数量）", category: "phrase" },
        { word: "mouse", meaning: "老鼠", category: "animal" },
        { word: "cat", meaning: "猫", category: "animal" },
        { word: "dog", meaning: "狗", category: "animal" },
        { word: "rabbit", meaning: "兔子", category: "animal" },
        { word: "fish", meaning: "鱼", category: "animal" },
        { word: "it's", meaning: "它是", category: "phrase" },
        { word: "tail", meaning: "尾巴", category: "body" },
        { word: "what", meaning: "什么", category: "question" },
        { word: "spring", meaning: "春天", category: "season" },
        { word: "summer", meaning: "夏天", category: "season" },
        { word: "autumn", meaning: "秋天", category: "season" },
        { word: "winter", meaning: "冬天", category: "season" },
        { word: "cold", meaning: "寒冷的", category: "adj" },
        { word: "cool", meaning: "凉爽的", category: "adj" },
        { word: "hot", meaning: "炎热的", category: "adj" },
        { word: "warm", meaning: "温暖的", category: "adj" },
        { word: "in", meaning: "在（某段时间）里", category: "prep" }
    ],

    "3-2": [
        { word: "black", meaning: "黑色", category: "color" },
        { word: "blue", meaning: "蓝色", category: "color" },
        { word: "green", meaning: "绿色", category: "color" },
        { word: "red", meaning: "红色", category: "color" },
        { word: "white", meaning: "白色", category: "color" },
        { word: "yellow", meaning: "黄色", category: "color" },
        { word: "and", meaning: "和", category: "conj" },
        { word: "ball", meaning: "球", category: "noun" },
        { word: "colour", meaning: "颜色", category: "noun" },
        { word: "candy", meaning: "糖果", category: "food" },
        { word: "ice cream", meaning: "冰淇淋", category: "food" },
        { word: "lemon", meaning: "柠檬", category: "food" },
        { word: "how", meaning: "怎样", category: "question" },
        { word: "orange", meaning: "橘子", category: "food" },
        { word: "sour", meaning: "酸的", category: "adj" },
        { word: "sweet", meaning: "甜的", category: "adj" },
        { word: "taste", meaning: "品尝", category: "verb" },
        { word: "bike", meaning: "自行车", category: "vehicle" },
        { word: "bus", meaning: "大客车", category: "vehicle" },
        { word: "plane", meaning: "飞机", category: "vehicle" },
        { word: "ship", meaning: "船", category: "vehicle" },
        { word: "car", meaning: "汽车", category: "vehicle" },
        { word: "train", meaning: "火车", category: "vehicle" },
        { word: "can", meaning: "能", category: "verb" },
        { word: "hear", meaning: "听见", category: "verb" },
        { word: "listen", meaning: "听", category: "verb" },
        { word: "bear", meaning: "熊", category: "animal" },
        { word: "elephant", meaning: "大象", category: "animal" },
        { word: "lion", meaning: "狮子", category: "animal" },
        { word: "monkey", meaning: "猴子", category: "animal" },
        { word: "panda", meaning: "熊猫", category: "animal" },
        { word: "tiger", meaning: "老虎", category: "animal" },
        { word: "like", meaning: "像，喜欢", category: "verb" },
        { word: "man", meaning: "男人", category: "person" },
        { word: "old", meaning: "旧的，老的", category: "adj" },
        { word: "our", meaning: "我们的", category: "pronoun" },
        { word: "strong", meaning: "强壮", category: "adj" },
        { word: "kite", meaning: "风筝", category: "toy" },
        { word: "robot", meaning: "机器人", category: "toy" },
        { word: "toy bear", meaning: "玩具熊", category: "toy" },
        { word: "fun", meaning: "有趣的", category: "adj" },
        { word: "lovely", meaning: "可爱的", category: "adj" },
        { word: "play", meaning: "玩", category: "verb" },
        { word: "sorry", meaning: "对不起", category: "phrase" },
        { word: "biscuit", meaning: "饼干", category: "food" },
        { word: "bread", meaning: "面包", category: "food" },
        { word: "egg", meaning: "鸡蛋", category: "food" },
        { word: "juice", meaning: "果汁", category: "drink" },
        { word: "milk", meaning: "牛奶", category: "drink" },
        { word: "water", meaning: "水", category: "drink" },
        { word: "breakfast", meaning: "早餐", category: "meal" },
        { word: "child", meaning: "孩子", category: "person" },
        { word: "have", meaning: "有", category: "verb" },
        { word: "some", meaning: "一些", category: "determiner" },
        { word: "too", meaning: "也", category: "adv" },
        { word: "we", meaning: "我们", category: "pronoun" },
        { word: "dance", meaning: "跳舞", category: "verb" },
        { word: "paint", meaning: "画画", category: "verb" },
        { word: "read", meaning: "读", category: "verb" },
        { word: "sing", meaning: "唱歌", category: "verb" },
        { word: "skate", meaning: "滑冰", category: "verb" },
        { word: "swim", meaning: "游泳", category: "verb" },
        { word: "at home", meaning: "在家", category: "phrase" },
        { word: "come in", meaning: "进来", category: "phrase" },
        { word: "sleep", meaning: "睡觉", category: "verb" },
        { word: "work", meaning: "工作", category: "verb" },
        { word: "worker", meaning: "工人", category: "job" },
        { word: "cake", meaning: "蛋糕", category: "food" },
        { word: "card", meaning: "卡片", category: "noun" },
        { word: "noodle", meaning: "面条", category: "food" },
        { word: "birthday", meaning: "生日", category: "time" },
        { word: "dear", meaning: "亲爱的", category: "adj" },
        { word: "for", meaning: "为了", category: "prep" },
        { word: "how old", meaning: "多大（年纪）", category: "phrase" },
        { word: "to", meaning: "向，朝着", category: "prep" },
        { word: "cow", meaning: "牛", category: "animal" },
        { word: "horse", meaning: "马", category: "animal" },
        { word: "pig", meaning: "猪", category: "animal" },
        { word: "sheep", meaning: "羊", category: "animal" },
        { word: "bye", meaning: "再见", category: "greeting" },
        { word: "farm", meaning: "农场", category: "place" },
        { word: "grass", meaning: "草", category: "nature" },
        { word: "great", meaning: "好，伟大的", category: "adj" },
        { word: "litter", meaning: "垃圾", category: "noun" },
        { word: "stone", meaning: "石头", category: "nature" },
        { word: "throw", meaning: "扔", category: "verb" },
        { word: "head", meaning: "头", category: "body" },
        { word: "body", meaning: "身体", category: "body" },
        { word: "arm", meaning: "胳膊", category: "body" },
        { word: "hand", meaning: "手", category: "body" },
        { word: "leg", meaning: "腿", category: "body" },
        { word: "foot", meaning: "脚", category: "body" },
        { word: "flower", meaning: "花", category: "nature" },
        { word: "photo", meaning: "照片", category: "noun" },
        { word: "tea", meaning: "茶", category: "drink" },
        { word: "cup", meaning: "杯子", category: "noun" },
        { word: "day", meaning: "天，白天", category: "time" },
        { word: "idea", meaning: "主意", category: "noun" },
        { word: "love", meaning: "爱", category: "verb" },
        { word: "afraid of", meaning: "害怕", category: "phrase" },
        { word: "bad", meaning: "坏的", category: "adj" },
        { word: "house", meaning: "房子", category: "place" },
        { word: "little", meaning: "小，一点儿", category: "adj" },
        { word: "make", meaning: "做，制造", category: "verb" },
        { word: "now", meaning: "现在", category: "time" },
        { word: "there", meaning: "那里", category: "place" },
        { word: "very", meaning: "非常", category: "adv" }
    ],

    "4-1": [
        { word: "meet", meaning: "相识", category: "verb" },
        { word: "new", meaning: "新的", category: "adj" },
        { word: "morning", meaning: "早晨", category: "time" },
        { word: "classmate", meaning: "同学", category: "person" },
        { word: "her", meaning: "她的", category: "pronoun" },
        { word: "name", meaning: "名字", category: "noun" },
        { word: "sit", meaning: "坐", category: "verb" },
        { word: "afternoon", meaning: "下午", category: "time" },
        { word: "his", meaning: "他的", category: "pronoun" },
        { word: "run", meaning: "跑", category: "verb" },
        { word: "fast", meaning: "快", category: "adj" },
        { word: "fly", meaning: "飞", category: "verb" },
        { word: "draw", meaning: "画画", category: "verb" },
        { word: "write", meaning: "写字", category: "verb" },
        { word: "jump", meaning: "跳", category: "verb" },
        { word: "welcome", meaning: "欢迎", category: "phrase" },
        { word: "woof", meaning: "汪汪", category: "sound" },
        { word: "but", meaning: "但是", category: "conj" },
        { word: "happy", meaning: "开心的", category: "adj" },
        { word: "sad", meaning: "难过的", category: "adj" },
        { word: "tired", meaning: "累的", category: "adj" },
        { word: "hungry", meaning: "饥饿的", category: "adj" },
        { word: "full", meaning: "饱的", category: "adj" },
        { word: "thirsty", meaning: "口渴的", category: "adj" },
        { word: "bird", meaning: "鸟", category: "animal" },
        { word: "see", meaning: "看见", category: "verb" },
        { word: "bottle", meaning: "瓶子", category: "noun" },
        { word: "drink", meaning: "喝", category: "verb" },
        { word: "any", meaning: "任何", category: "determiner" },
        { word: "cousin", meaning: "表兄弟，表姐妹", category: "family" },
        { word: "family", meaning: "家庭", category: "noun" },
        { word: "parent", meaning: "父母亲", category: "family" },
        { word: "grandparent", meaning: "祖父母，外祖父母", category: "family" },
        { word: "son", meaning: "儿子", category: "family" },
        { word: "grandfather", meaning: "外公（爷爷）", category: "family" },
        { word: "grandpa", meaning: "外公（爷爷）", category: "family" },
        { word: "grandmother", meaning: "外婆（奶奶）", category: "family" },
        { word: "grandma", meaning: "外婆（奶奶）", category: "family" },
        { word: "uncle", meaning: "叔叔，舅舅", category: "family" },
        { word: "aunt", meaning: "姑妈，阿姨", category: "family" },
        { word: "that", meaning: "那个", category: "pronoun" },
        { word: "T-shirt", meaning: "T 恤衫", category: "clothes" },
        { word: "brown", meaning: "棕色", category: "color" },
        { word: "shorts", meaning: "短裤", category: "clothes" },
        { word: "ride", meaning: "骑", category: "verb" },
        { word: "skirt", meaning: "短裙", category: "clothes" },
        { word: "dress", meaning: "连衣裙", category: "clothes" },
        { word: "shirt", meaning: "衬衫", category: "clothes" },
        { word: "tooth", meaning: "牙齿", category: "body" },
        { word: "sharp", meaning: "锋利", category: "adj" },
        { word: "help", meaning: "帮助", category: "verb" },
        { word: "get out", meaning: "出去", category: "phrase" },
        { word: "nurse", meaning: "护士", category: "job" },
        { word: "fireman", meaning: "消防员", category: "job" },
        { word: "teacher", meaning: "教师", category: "job" },
        { word: "doctor", meaning: "医生", category: "job" },
        { word: "bus driver", meaning: "公共汽车司机", category: "job" },
        { word: "kid", meaning: "小孩", category: "person" },
        { word: "so", meaning: "如此", category: "adv" },
        { word: "fire", meaning: "火", category: "noun" },
        { word: "people", meaning: "人们", category: "person" },
        { word: "job", meaning: "工作，职业", category: "noun" },
        { word: "school", meaning: "学校", category: "place" },
        { word: "office", meaning: "办公室", category: "place" },
        { word: "busy", meaning: "繁忙", category: "adj" },
        { word: "computer", meaning: "电脑", category: "noun" },
        { word: "many", meaning: "许多", category: "determiner" },
        { word: "library", meaning: "图书馆", category: "place" },
        { word: "playground", meaning: "操场", category: "place" },
        { word: "classroom", meaning: "教室", category: "place" },
        { word: "toilet", meaning: "厕所", category: "place" },
        { word: "animal", meaning: "动物", category: "animal" },
        { word: "forest", meaning: "森林", category: "nature" },
        { word: "pupil", meaning: "小学生", category: "person" },
        { word: "try", meaning: "尝试", category: "verb" },
        { word: "first", meaning: "第一", category: "number" },
        { word: "shop", meaning: "商店", category: "place" },
        { word: "tomato", meaning: "西红柿", category: "food" },
        { word: "soup", meaning: "汤", category: "food" },
        { word: "potato", meaning: "土豆", category: "food" },
        { word: "carrot", meaning: "胡萝卜", category: "food" },
        { word: "thirty", meaning: "三十", category: "number" },
        { word: "fish", meaning: "鱼", category: "food" },
        { word: "meat", meaning: "肉", category: "food" },
        { word: "rice", meaning: "米饭", category: "food" },
        { word: "glasses", meaning: "眼镜", category: "clothes" },
        { word: "want", meaning: "想要", category: "verb" },
        { word: "together", meaning: "一起", category: "adv" },
        { word: "magic", meaning: "神奇", category: "adj" },
        { word: "need", meaning: "需要", category: "verb" },
        { word: "where", meaning: "哪里", category: "question" },
        { word: "in", meaning: "在……里面", category: "prep" },
        { word: "box", meaning: "盒子", category: "noun" },
        { word: "give", meaning: "给", category: "verb" },
        { word: "plate", meaning: "盘子", category: "noun" },
        { word: "on", meaning: "在……上面", category: "prep" },
        { word: "table", meaning: "桌子", category: "furniture" },
        { word: "lunch", meaning: "午餐", category: "meal" },
        { word: "under", meaning: "在……下面", category: "prep" },
        { word: "beside", meaning: "在……旁边", category: "prep" },
        { word: "kitchen", meaning: "厨房", category: "room" },
        { word: "floor", meaning: "地板", category: "noun" },
        { word: "angry", meaning: "生气的", category: "adj" },
        { word: "around", meaning: "到处", category: "adv" },
        { word: "home", meaning: "家", category: "place" },
        { word: "street", meaning: "街道", category: "place" },
        { word: "park", meaning: "公园", category: "place" },
        { word: "near", meaning: "附近", category: "prep" },
        { word: "behind", meaning: "在……后面", category: "prep" },
        { word: "supermarket", meaning: "超市", category: "place" },
        { word: "restaurant", meaning: "餐馆", category: "place" },
        { word: "live", meaning: "居住", category: "verb" },
        { word: "old", meaning: "古老的", category: "adj" },
        { word: "eat", meaning: "吃", category: "verb" },
        { word: "nice", meaning: "美味的", category: "adj" },
        { word: "food", meaning: "食物", category: "food" },
        { word: "a lot of", meaning: "很多", category: "phrase" },
        { word: "shape", meaning: "形状", category: "noun" },
        { word: "picture", meaning: "图画", category: "noun" },
        { word: "square", meaning: "正方形", category: "shape" },
        { word: "circle", meaning: "圆形", category: "shape" },
        { word: "star", meaning: "五角星", category: "shape" },
        { word: "rectangle", meaning: "长方形", category: "shape" },
        { word: "triangle", meaning: "三角形", category: "shape" },
        { word: "today", meaning: "今天", category: "time" },
        { word: "well", meaning: "好，健康", category: "adj" },
        { word: "weather", meaning: "天气", category: "noun" },
        { word: "rainy", meaning: "多雨的", category: "weather" },
        { word: "cloudy", meaning: "多云的", category: "weather" },
        { word: "windy", meaning: "多风的", category: "weather" },
        { word: "sunny", meaning: "阳光充足的", category: "weather" },
        { word: "Sunday", meaning: "星期天", category: "day" },
        { word: "cloud", meaning: "云", category: "nature" },
        { word: "rain", meaning: "雨", category: "nature" },
        { word: "sun", meaning: "太阳", category: "nature" },
        { word: "wind", meaning: "风", category: "nature" }
    ],

    "4-2": [
        { word: "touch", meaning: "碰，触摸", category: "verb" },
        { word: "feel", meaning: "摸起来，感到", category: "verb" },
        { word: "soft", meaning: "柔软的", category: "adj" },
        { word: "hard", meaning: "坚硬的", category: "adj" },
        { word: "thick", meaning: "厚的，粗的", category: "adj" },
        { word: "thin", meaning: "薄的，细的", category: "adj" },
        { word: "blind", meaning: "瞎的，失明的", category: "adj" },
        { word: "noise", meaning: "响声，吵闹声", category: "noun" },
        { word: "young", meaning: "年轻的", category: "adj" },
        { word: "smell", meaning: "闻，嗅", category: "verb" },
        { word: "strawberry", meaning: "草莓", category: "food" },
        { word: "or", meaning: "或者，还是", category: "conj" },
        { word: "watermelon", meaning: "西瓜", category: "food" },
        { word: "grape", meaning: "葡萄", category: "food" },
        { word: "fox", meaning: "狐狸", category: "animal" },
        { word: "round", meaning: "圆的", category: "adj" },
        { word: "purple", meaning: "紫色的", category: "color" },
        { word: "wait", meaning: "等待，等候", category: "verb" },
        { word: "minute", meaning: "一会儿，分钟", category: "time" },
        { word: "get", meaning: "得到", category: "verb" },
        { word: "those", meaning: "那些", category: "pronoun" },
        { word: "rise", meaning: "升起", category: "verb" },
        { word: "shadow", meaning: "影子", category: "noun" },
        { word: "noon", meaning: "中午", category: "time" },
        { word: "high", meaning: "高的", category: "adj" },
        { word: "sky", meaning: "天空", category: "nature" },
        { word: "evening", meaning: "黄昏，晚上", category: "time" },
        { word: "again", meaning: "再，又", category: "adv" },
        { word: "night", meaning: "夜晚", category: "time" },
        { word: "moon", meaning: "月亮", category: "nature" },
        { word: "him", meaning: "他", category: "pronoun" },
        { word: "stop", meaning: "停下", category: "verb" },
        { word: "at noon", meaning: "在中午", category: "phrase" },
        { word: "go down", meaning: "落下", category: "phrase" },
        { word: "at night", meaning: "在夜晚", category: "phrase" },
        { word: "take a walk", meaning: "散步", category: "phrase" },
        { word: "subject", meaning: "学科，科目", category: "noun" },
        { word: "lesson", meaning: "课", category: "noun" },
        { word: "Chinese", meaning: "语文", category: "subject" },
        { word: "Maths", meaning: "数学", category: "subject" },
        { word: "English", meaning: "英语", category: "subject" },
        { word: "Science", meaning: "科学", category: "subject" },
        { word: "PE", meaning: "体育", category: "subject" },
        { word: "Music", meaning: "音乐", category: "subject" },
        { word: "Art", meaning: "美术", category: "subject" },
        { word: "timetable", meaning: "课程表", category: "school" },
        { word: "from", meaning: "从", category: "prep" },
        { word: "a.m.", meaning: "上午", category: "time" },
        { word: "p.m.", meaning: "下午", category: "time" },
        { word: "break", meaning: "休息", category: "noun" },
        { word: "from...to...", meaning: "从……到……", category: "phrase" },
        { word: "sport", meaning: "体育运动", category: "activity" },
        { word: "football", meaning: "足球", category: "sport" },
        { word: "club", meaning: "俱乐部", category: "noun" },
        { word: "join", meaning: "参加", category: "verb" },
        { word: "tell", meaning: "告诉", category: "verb" },
        { word: "about", meaning: "关于", category: "prep" },
        { word: "basketball", meaning: "篮球", category: "sport" },
        { word: "volleyball", meaning: "排球", category: "sport" },
        { word: "us", meaning: "我们", category: "pronoun" },
        { word: "table tennis", meaning: "乒乓球运动", category: "sport" },
        { word: "play football", meaning: "踢足球", category: "phrase" },
        { word: "play basketball", meaning: "打篮球", category: "phrase" },
        { word: "play volleyball", meaning: "打排球", category: "phrase" },
        { word: "wonderful", meaning: "使人愉悦的，绝妙的", category: "adj" },
        { word: "violin", meaning: "小提琴", category: "instrument" },
        { word: "guitar", meaning: "吉他", category: "instrument" },
        { word: "whose", meaning: "谁的", category: "question" },
        { word: "piano", meaning: "钢琴", category: "instrument" },
        { word: "city", meaning: "城市", category: "place" },
        { word: "bag", meaning: "袋子", category: "noun" },
        { word: "all", meaning: "全部", category: "determiner" },
        { word: "play the violin", meaning: "拉小提琴", category: "phrase" },
        { word: "play the guitar", meaning: "弹吉他", category: "phrase" },
        { word: "o'clock", meaning: "……点钟", category: "time" },
        { word: "quarter", meaning: "一刻钟", category: "time" },
        { word: "time", meaning: "时间", category: "time" },
        { word: "half", meaning: "半，一半", category: "number" },
        { word: "wash", meaning: "洗", category: "verb" },
        { word: "dinner", meaning: "晚餐，正餐", category: "meal" },
        { word: "start", meaning: "开始", category: "verb" },
        { word: "catch", meaning: "捉住", category: "verb" },
        { word: "get up", meaning: "起床", category: "phrase" },
        { word: "brush teeth", meaning: "刷牙", category: "phrase" },
        { word: "half past", meaning: "……点半", category: "phrase" },
        { word: "have breakfast", meaning: "吃早餐", category: "phrase" },
        { word: "go to school", meaning: "去上学", category: "phrase" },
        { word: "wash face", meaning: "洗脸", category: "phrase" },
        { word: "have lunch", meaning: "吃午餐", category: "phrase" },
        { word: "have dinner", meaning: "吃晚餐", category: "phrase" },
        { word: "go to bed", meaning: "上床睡觉", category: "phrase" },
        { word: "week", meaning: "星期，周", category: "time" },
        { word: "Monday", meaning: "星期一", category: "day" },
        { word: "with", meaning: "和……一起", category: "prep" },
        { word: "Tuesday", meaning: "星期二", category: "day" },
        { word: "Wednesday", meaning: "星期三", category: "day" },
        { word: "Thursday", meaning: "星期四", category: "day" },
        { word: "Friday", meaning: "星期五", category: "day" },
        { word: "game", meaning: "游戏", category: "activity" },
        { word: "Saturday", meaning: "星期六", category: "day" },
        { word: "Sunday", meaning: "星期日", category: "day" },
        { word: "clock", meaning: "时钟，钟", category: "noun" },
        { word: "play chess", meaning: "下国际象棋", category: "phrase" },
        { word: "at the weekend", meaning: "在周末", category: "phrase" },
        { word: "be late for", meaning: "迟到", category: "phrase" },
        { word: "China", meaning: "中国", category: "country" },
        { word: "talk", meaning: "谈话，说话", category: "verb" },
        { word: "May", meaning: "五月", category: "month" },
        { word: "June", meaning: "六月", category: "month" },
        { word: "January", meaning: "一月", category: "month" },
        { word: "February", meaning: "二月", category: "month" },
        { word: "March", meaning: "三月", category: "month" },
        { word: "April", meaning: "四月", category: "month" },
        { word: "July", meaning: "七月", category: "month" },
        { word: "August", meaning: "八月", category: "month" },
        { word: "September", meaning: "九月", category: "month" },
        { word: "October", meaning: "十月", category: "month" },
        { word: "November", meaning: "十一月", category: "month" },
        { word: "December", meaning: "十二月", category: "month" },
        { word: "email", meaning: "电子邮件", category: "noun" },
        { word: "hat", meaning: "帽子", category: "clothes" },
        { word: "wear", meaning: "穿，戴", category: "verb" },
        { word: "yours", meaning: "你的，你们的", category: "pronoun" },
        { word: "every year", meaning: "每年", category: "phrase" },
        { word: "garden", meaning: "花园", category: "place" },
        { word: "plant", meaning: "植物", category: "nature" },
        { word: "leaf", meaning: "叶子", category: "nature" },
        { word: "water", meaning: "给……浇水", category: "verb" },
        { word: "them", meaning: "它们，他们，她们", category: "pronoun" },
        { word: "grow", meaning: "生长，成长", category: "verb" },
        { word: "seed", meaning: "种子", category: "nature" },
        { word: "every day", meaning: "每天", category: "phrase" },
        { word: "song", meaning: "歌曲", category: "noun" },
        { word: "zoo", meaning: "动物园", category: "place" },
        { word: "cinema", meaning: "电影院", category: "place" },
        { word: "museum", meaning: "博物馆", category: "place" },
        { word: "also", meaning: "也，还", category: "adv" },
        { word: "have a party", meaning: "举办聚会", category: "phrase" },
        { word: "ugly", meaning: "丑的，丑陋的", category: "adj" },
        { word: "duck", meaning: "鸭子", category: "animal" },
        { word: "duckling", meaning: "小鸭子", category: "animal" },
        { word: "river", meaning: "河，江", category: "nature" },
        { word: "baby", meaning: "宝宝，婴儿", category: "person" },
        { word: "later", meaning: "后来，以后", category: "adv" },
        { word: "quack", meaning: "嘎嘎", category: "sound" },
        { word: "back", meaning: "背，背部", category: "body" },
        { word: "away", meaning: "去别处，朝另一个方向", category: "adv" },
        { word: "swan", meaning: "天鹅", category: "animal" },
        { word: "into", meaning: "朝，向，到……里面", category: "prep" }
    ],

    "5-1": [
        { word: "future", meaning: "未来", category: "noun" },
        { word: "want", meaning: "想要", category: "verb" },
        { word: "pilot", meaning: "飞行员", category: "job" },
        { word: "teach", meaning: "教", category: "verb" },
        { word: "cook", meaning: "厨师，烹饪", category: "job" },
        { word: "taxi driver", meaning: "出租车司机", category: "job" },
        { word: "job", meaning: "工作，职业", category: "noun" },
        { word: "singer", meaning: "歌手", category: "job" },
        { word: "fall", meaning: "掉落", category: "verb" },
        { word: "lifeguard", meaning: "救生员", category: "job" },
        { word: "save", meaning: "救", category: "verb" },
        { word: "become", meaning: "变成，变得", category: "verb" },
        { word: "be good at", meaning: "擅长", category: "phrase" },
        { word: "by", meaning: "靠近，乘", category: "prep" },
        { word: "walk", meaning: "走，步行", category: "verb" },
        { word: "Ms", meaning: "女士", category: "title" },
        { word: "journey", meaning: "旅程", category: "noun" },
        { word: "primary school", meaning: "小学", category: "place" },
        { word: "underground", meaning: "地铁", category: "vehicle" },
        { word: "station", meaning: "车站", category: "place" },
        { word: "take", meaning: "乘坐，带领", category: "verb" },
        { word: "after", meaning: "在……之后", category: "prep" },
        { word: "hour", meaning: "小时", category: "time" },
        { word: "bus stop", meaning: "公共汽车站", category: "place" },
        { word: "by bus", meaning: "乘公共汽车", category: "phrase" },
        { word: "far from", meaning: "离……远", category: "phrase" },
        { word: "on foot", meaning: "步行", category: "phrase" },
        { word: "by bike", meaning: "骑自行车", category: "phrase" },
        { word: "by car", meaning: "乘小汽车", category: "phrase" },
        { word: "get off", meaning: "下车", category: "phrase" },
        { word: "party", meaning: "聚会", category: "activity" },
        { word: "when", meaning: "什么时候", category: "question" },
        { word: "begin", meaning: "开始", category: "verb" },
        { word: "bring", meaning: "带来", category: "verb" },
        { word: "thing", meaning: "东西", category: "noun" },
        { word: "favourite", meaning: "最喜欢的", category: "adj" },
        { word: "interesting", meaning: "有趣的", category: "adj" },
        { word: "hat", meaning: "帽子", category: "clothes" },
        { word: "have fun", meaning: "尽情玩", category: "phrase" },
        { word: "usually", meaning: "通常", category: "adv" },
        { word: "often", meaning: "经常", category: "adv" },
        { word: "visit", meaning: "看望，拜访", category: "verb" },
        { word: "sometimes", meaning: "有时", category: "adv" },
        { word: "always", meaning: "总是，一直", category: "adv" },
        { word: "never", meaning: "从不", category: "adv" },
        { word: "play sport", meaning: "做运动", category: "phrase" },
        { word: "go shopping", meaning: "去购物", category: "phrase" },
        { word: "clever", meaning: "聪明的", category: "adj" },
        { word: "same", meaning: "相同的", category: "adj" },
        { word: "class", meaning: "班级", category: "school" },
        { word: "both", meaning: "（两个）都", category: "determiner" },
        { word: "cross", meaning: "穿越，越过", category: "verb" },
        { word: "carry", meaning: "背，提", category: "verb" },
        { word: "heavy", meaning: "重的", category: "adj" },
        { word: "different", meaning: "不同的", category: "adj" },
        { word: "bored", meaning: "无聊的", category: "adj" },
        { word: "word", meaning: "单词", category: "noun" },
        { word: "easy", meaning: "容易的", category: "adj" },
        { word: "say", meaning: "说", category: "verb" },
        { word: "then", meaning: "然后，那么", category: "adv" },
        { word: "ask", meaning: "问", category: "verb" },
        { word: "answer", meaning: "回答", category: "verb" },
        { word: "soon", meaning: "很快，不久", category: "adv" },
        { word: "each other", meaning: "互相", category: "phrase" },
        { word: "make phone calls", meaning: "打电话", category: "phrase" },
        { word: "life", meaning: "生活", category: "noun" },
        { word: "living room", meaning: "客厅", category: "room" },
        { word: "bedroom", meaning: "卧室", category: "room" },
        { word: "model plane", meaning: "飞机模型", category: "toy" },
        { word: "kitchen", meaning: "厨房", category: "room" },
        { word: "bathroom", meaning: "浴室，卫生间", category: "room" },
        { word: "their", meaning: "他们的", category: "pronoun" },
        { word: "light", meaning: "灯，光", category: "noun" },
        { word: "watch", meaning: "观看", category: "verb" },
        { word: "TV", meaning: "电视机", category: "noun" },
        { word: "before", meaning: "在……以前", category: "prep" },
        { word: "bedtime", meaning: "就寝时间", category: "time" },
        { word: "do homework", meaning: "做家庭作业", category: "phrase" },
        { word: "turn off", meaning: "关掉", category: "phrase" },
        { word: "watch TV", meaning: "看电视", category: "phrase" },
        { word: "tell a story", meaning: "讲故事", category: "phrase" },
        { word: "beach", meaning: "海滩", category: "place" },
        { word: "enjoy", meaning: "享受……的乐趣", category: "verb" },
        { word: "sunshine", meaning: "阳光", category: "nature" },
        { word: "collect", meaning: "收集", category: "verb" },
        { word: "shell", meaning: "贝壳", category: "nature" },
        { word: "sea", meaning: "海", category: "nature" },
        { word: "letter", meaning: "信", category: "noun" },
        { word: "put", meaning: "放，安置", category: "verb" },
        { word: "know", meaning: "知道", category: "verb" },
        { word: "year", meaning: "年岁，年", category: "time" },
        { word: "on holiday", meaning: "度假", category: "phrase" },
        { word: "have a good time", meaning: "玩得高兴", category: "phrase" },
        { word: "outing", meaning: "远足", category: "activity" },
        { word: "map", meaning: "地图", category: "noun" },
        { word: "hill", meaning: "山丘", category: "nature" },
        { word: "find", meaning: "找到", category: "verb" },
        { word: "diamond", meaning: "钻石", category: "noun" },
        { word: "another", meaning: "另一个", category: "determiner" },
        { word: "lake", meaning: "湖", category: "nature" },
        { word: "funny", meaning: "滑稽的，好笑的", category: "adj" },
        { word: "hole", meaning: "洞", category: "noun" },
        { word: "key", meaning: "钥匙", category: "noun" },
        { word: "think", meaning: "想", category: "verb" },
        { word: "at the top of", meaning: "在……顶部", category: "phrase" },
        { word: "get through", meaning: "通过", category: "phrase" },
        { word: "post office", meaning: "邮局", category: "place" },
        { word: "quite", meaning: "相当，十分", category: "adv" },
        { word: "along", meaning: "沿着，顺着", category: "prep" },
        { word: "turn", meaning: "转向，转弯", category: "verb" },
        { word: "left", meaning: "左边", category: "direction" },
        { word: "straight", meaning: "笔直地", category: "adv" },
        { word: "right", meaning: "右边，正确的", category: "direction" },
        { word: "between", meaning: "在……中间", category: "prep" },
        { word: "flower shop", meaning: "花店", category: "place" },
        { word: "hospital", meaning: "医院", category: "place" },
        { word: "toy shop", meaning: "玩具店", category: "place" },
        { word: "road", meaning: "路，马路", category: "place" },
        { word: "get to", meaning: "到达", category: "phrase" },
        { word: "gently", meaning: "和缓地，温柔地", category: "adv" },
        { word: "blow", meaning: "刮，吹", category: "verb" },
        { word: "softly", meaning: "轻柔地", category: "adv" },
        { word: "strongly", meaning: "强劲地", category: "adv" },
        { word: "happily", meaning: "快乐地", category: "adv" },
        { word: "windmill", meaning: "风车", category: "noun" },
        { word: "move", meaning: "移动", category: "verb" },
        { word: "slowly", meaning: "缓慢地", category: "adv" },
        { word: "quickly", meaning: "迅速地", category: "adv" },
        { word: "sound", meaning: "声音，听起来好像", category: "noun" },
        { word: "wind-bell", meaning: "风铃", category: "noun" },
        { word: "cut", meaning: "剪，砍", category: "verb" },
        { word: "paper", meaning: "纸", category: "noun" },
        { word: "quiet", meaning: "轻声的", category: "adj" },
        { word: "tap", meaning: "水龙头", category: "noun" },
        { word: "use", meaning: "使用", category: "verb" },
        { word: "vegetables", meaning: "蔬菜", category: "food" },
        { word: "clothes", meaning: "衣服", category: "clothes" },
        { word: "farmer", meaning: "农民", category: "job" },
        { word: "useful", meaning: "有用的", category: "adj" },
        { word: "drop", meaning: "滴，水珠", category: "noun" },
        { word: "up", meaning: "向上", category: "direction" },
        { word: "shine", meaning: "照耀", category: "verb" },
        { word: "over", meaning: "在……上方", category: "prep" },
        { word: "mountain", meaning: "山，山脉", category: "nature" },
        { word: "tree", meaning: "树", category: "nature" },
        { word: "ground", meaning: "地面", category: "nature" },
        { word: "inside", meaning: "在……里面", category: "prep" },
        { word: "grow crops", meaning: "种庄稼", category: "phrase" },
        { word: "put out fire", meaning: "灭火", category: "phrase" },
        { word: "fire", meaning: "火", category: "noun" },
        { word: "burn", meaning: "燃烧", category: "verb" },
        { word: "hurt", meaning: "（使）受伤", category: "verb" },
        { word: "must", meaning: "必须", category: "verb" },
        { word: "careful", meaning: "小心的", category: "adj" },
        { word: "safety", meaning: "安全", category: "noun" },
        { word: "smoke", meaning: "吸烟", category: "verb" },
        { word: "match", meaning: "火柴", category: "noun" },
        { word: "heat", meaning: "热，高温", category: "noun" },
        { word: "hate", meaning: "讨厌", category: "verb" },
        { word: "burn down", meaning: "烧毁", category: "phrase" },
        { word: "be careful with", meaning: "当心……", category: "phrase" },
        { word: "not...at all", meaning: "一点也不……", category: "phrase" }
    ],

    "5-2": [
        { word: "tidy", meaning: "整理", category: "verb" },
        { word: "mess", meaning: "脏乱，不整洁", category: "noun" },
        { word: "let", meaning: "让", category: "verb" },
        { word: "sock", meaning: "短袜", category: "clothes" },
        { word: "yours", meaning: "你的，你们的", category: "pronoun" },
        { word: "cap", meaning: "帽子", category: "clothes" },
        { word: "mine", meaning: "我的", category: "pronoun" },
        { word: "crayon", meaning: "蜡笔", category: "school" },
        { word: "umbrella", meaning: "雨伞", category: "noun" },
        { word: "nail", meaning: "钉子", category: "noun" },
        { word: "drop", meaning: "使落下", category: "verb" },
        { word: "stick", meaning: "粘贴", category: "verb" },
        { word: "second", meaning: "秒", category: "time" },
        { word: "hers", meaning: "她的", category: "pronoun" },
        { word: "theirs", meaning: "他们的", category: "pronoun" },
        { word: "tidy up", meaning: "把……整理好", category: "phrase" },
        { word: "be full of", meaning: "装满……", category: "phrase" },
        { word: "a few", meaning: "几个，一些", category: "phrase" },
        { word: "why", meaning: "为什么", category: "question" },
        { word: "because", meaning: "因为", category: "conj" },
        { word: "study", meaning: "书房，学习", category: "noun" },
        { word: "dining room", meaning: "餐厅", category: "room" },
        { word: "wild goose", meaning: "大雁", category: "animal" },
        { word: "change", meaning: "改变", category: "verb" },
        { word: "place", meaning: "地方", category: "place" },
        { word: "twice", meaning: "两次", category: "adv" },
        { word: "every", meaning: "每个", category: "determiner" },
        { word: "north", meaning: "北方", category: "direction" },
        { word: "south", meaning: "南方", category: "direction" },
        { word: "enough", meaning: "足够的", category: "adj" },
        { word: "then", meaning: "然后", category: "adv" },
        { word: "all day", meaning: "一天到晚", category: "phrase" },
        { word: "future", meaning: "未来", category: "noun" },
        { word: "stand", meaning: "站", category: "verb" },
        { word: "machine", meaning: "机器", category: "noun" },
        { word: "will", meaning: "将", category: "verb" },
        { word: "exercise", meaning: "运动", category: "noun" },
        { word: "early", meaning: "早，提早", category: "adv" },
        { word: "easily", meaning: "容易地", category: "adv" },
        { word: "hard", meaning: "努力地", category: "adv" },
        { word: "more", meaning: "更多的", category: "adj" },
        { word: "in the future", meaning: "将来", category: "phrase" },
        { word: "in front of", meaning: "在……前面", category: "phrase" },
        { word: "take a photo", meaning: "拍照", category: "phrase" },
        { word: "wear glasses", meaning: "戴眼镜", category: "phrase" },
        { word: "do exercise", meaning: "做运动", category: "phrase" },
        { word: "be weak in", meaning: "不擅长", category: "phrase" },
        { word: "not...any more", meaning: "不再", category: "phrase" },
        { word: "storybook", meaning: "故事书", category: "book" },
        { word: "buy", meaning: "买", category: "verb" },
        { word: "story", meaning: "故事", category: "noun" },
        { word: "dictionary", meaning: "字典", category: "book" },
        { word: "magazine", meaning: "杂志", category: "book" },
        { word: "newspaper", meaning: "报纸", category: "book" },
        { word: "week", meaning: "周", category: "time" },
        { word: "student", meaning: "学生", category: "person" },
        { word: "poster", meaning: "海报", category: "noun" },
        { word: "best", meaning: "最好的", category: "adj" },
        { word: "writer", meaning: "作家", category: "job" },
        { word: "over there", meaning: "在那边", category: "phrase" },
        { word: "do a survey", meaning: "做调查", category: "phrase" },
        { word: "act out", meaning: "表演", category: "phrase" },
        { word: "weekend", meaning: "周末", category: "time" },
        { word: "stay", meaning: "待，暂住", category: "verb" },
        { word: "film", meaning: "电影", category: "noun" },
        { word: "boat", meaning: "小船", category: "vehicle" },
        { word: "plan", meaning: "安排，计划", category: "verb" },
        { word: "tomorrow", meaning: "明天", category: "time" },
        { word: "build", meaning: "建筑，建造", category: "verb" },
        { word: "next", meaning: "紧接着", category: "adj" },
        { word: "swing", meaning: "秋千", category: "noun" },
        { word: "cry", meaning: "哭，喊叫", category: "verb" },
        { word: "until", meaning: "直到", category: "prep" },
        { word: "see a film", meaning: "看电影", category: "phrase" },
        { word: "row a boat", meaning: "划船", category: "phrase" },
        { word: "holiday", meaning: "假日", category: "time" },
        { word: "clear", meaning: "清澈的", category: "adj" },
        { word: "seafood", meaning: "海鲜", category: "food" },
        { word: "hotel", meaning: "旅馆", category: "place" },
        { word: "island", meaning: "岛", category: "nature" },
        { word: "butterfly", meaning: "蝴蝶", category: "animal" },
        { word: "how long", meaning: "多久", category: "phrase" },
        { word: "go swimming", meaning: "去游泳", category: "phrase" },
        { word: "in the south of", meaning: "在……的南部", category: "phrase" },
        { word: "all year round", meaning: "一年到头", category: "phrase" },
        { word: "meet", meaning: "迎接，会见", category: "verb" },
        { word: "school gate", meaning: "校门", category: "place" },
        { word: "art room", meaning: "美术室", category: "place" },
        { word: "hall", meaning: "礼堂", category: "place" },
        { word: "finally", meaning: "最后", category: "adv" },
        { word: "meeting room", meaning: "会议室", category: "place" },
        { word: "show", meaning: "给……看", category: "verb" },
        { word: "project", meaning: "课题", category: "noun" },
        { word: "board", meaning: "布告牌", category: "noun" },
        { word: "which", meaning: "哪一个", category: "question" },
        { word: "trousers", meaning: "裤子", category: "clothes" },
        { word: "size", meaning: "尺寸", category: "noun" },
        { word: "sweater", meaning: "毛衣", category: "clothes" },
        { word: "coat", meaning: "外套", category: "clothes" },
        { word: "shoe", meaning: "鞋子", category: "clothes" },
        { word: "emperor", meaning: "皇帝", category: "person" },
        { word: "only", meaning: "只有", category: "adv" },
        { word: "nod", meaning: "点头", category: "verb" },
        { word: "smile", meaning: "微笑", category: "verb" },
        { word: "money", meaning: "钱", category: "noun" },
        { word: "keep", meaning: "保持", category: "verb" },
        { word: "laugh", meaning: "大笑", category: "verb" },
        { word: "try on", meaning: "试穿（衣物）", category: "phrase" },
        { word: "put on", meaning: "穿，戴", category: "phrase" },
        { word: "keep quiet", meaning: "保持安静", category: "phrase" },
        { word: "have a look", meaning: "看一看", category: "phrase" },
        { word: "ill", meaning: "生病的", category: "adj" },
        { word: "wrong", meaning: "有毛病，不正常", category: "adj" },
        { word: "headache", meaning: "头疼", category: "noun" },
        { word: "fever", meaning: "发烧", category: "noun" },
        { word: "should", meaning: "应该", category: "verb" },
        { word: "medicine", meaning: "药", category: "noun" },
        { word: "rest", meaning: "休息", category: "verb" },
        { word: "toothache", meaning: "牙痛", category: "noun" },
        { word: "toothless", meaning: "没有牙齿的", category: "adj" },
        { word: "present", meaning: "礼物", category: "noun" },
        { word: "world", meaning: "世界", category: "noun" },
        { word: "dentist", meaning: "牙医", category: "job" },
        { word: "have a headache", meaning: "头疼", category: "phrase" },
        { word: "have a fever", meaning: "发烧", category: "phrase" },
        { word: "have a cold", meaning: "感冒", category: "phrase" },
        { word: "have a rest", meaning: "休息一下", category: "phrase" },
        { word: "get well", meaning: "康复", category: "phrase" },
        { word: "have a toothache", meaning: "牙疼", category: "phrase" },
        { word: "have a meeting", meaning: "开会", category: "phrase" },
        { word: "pull out", meaning: "把……拔出", category: "phrase" },
        { word: "invention", meaning: "发明", category: "noun" },
        { word: "watch", meaning: "手表", category: "noun" },
        { word: "anywhere", meaning: "任何地方", category: "place" },
        { word: "travel", meaning: "旅行", category: "verb" },
        { word: "invent", meaning: "发明", category: "verb" },
        { word: "something", meaning: "某事，某物", category: "pronoun" },
        { word: "myself", meaning: "我自己", category: "pronoun" },
        { word: "camera", meaning: "相机", category: "noun" },
        { word: "far away from", meaning: "远离……", category: "phrase" },
        { word: "festival", meaning: "节日", category: "noun" },
        { word: "important", meaning: "重要的", category: "adj" },
        { word: "call", meaning: "把……叫做", category: "verb" },
        { word: "dumpling", meaning: "饺子", category: "food" },
        { word: "relative", meaning: "亲戚", category: "family" },
        { word: "red packet", meaning: "红包", category: "noun" },
        { word: "firework", meaning: "烟花", category: "noun" },
        { word: "monster", meaning: "怪物", category: "noun" },
        { word: "end", meaning: "结尾，结束", category: "noun" },
        { word: "village", meaning: "村庄", category: "place" },
        { word: "last", meaning: "最后的", category: "adj" },
        { word: "firecracker", meaning: "鞭炮", category: "noun" },
        { word: "mooncake", meaning: "月饼", category: "food" },
        { word: "at the end of", meaning: "在……最后", category: "phrase" },
        { word: "giant", meaning: "巨人", category: "person" },
        { word: "wall", meaning: "围墙", category: "noun" },
        { word: "kind", meaning: "友好的", category: "adj" },
        { word: "through", meaning: "穿过", category: "prep" },
        { word: "no entry", meaning: "禁止入内", category: "sign" },
        { word: "be kind to", meaning: "对……友好", category: "phrase" },
        { word: "knock down", meaning: "推倒，拆掉", category: "phrase" }
    ],

    "6-1": [
        { word: "month", meaning: "一个月的时间，月份", category: "time" },
        { word: "cute", meaning: "可爱的", category: "adj" },
        { word: "pretty", meaning: "漂亮的", category: "adj" },
        { word: "handsome", meaning: "英俊的，帅气的", category: "adj" },
        { word: "turtle", meaning: "乌龟", category: "animal" },
        { word: "catch", meaning: "逮住，捕捉", category: "verb" },
        { word: "fly", meaning: "苍蝇", category: "animal" },
        { word: "grow up", meaning: "长大，成长", category: "phrase" },
        { word: "junior high school", meaning: "初级中学", category: "place" },
        { word: "famous", meaning: "著名的，出名的", category: "adj" },
        { word: "during", meaning: "在……期间", category: "prep" },
        { word: "spend", meaning: "度过", category: "verb" },
        { word: "everyone", meaning: "每个人，所有人", category: "pronoun" },
        { word: "countryside", meaning: "乡村，农村", category: "place" },
        { word: "pick", meaning: "采摘", category: "verb" },
        { word: "summer holiday", meaning: "暑假", category: "time" },
        { word: "healthy", meaning: "健康的，有益于健康的", category: "adj" },
        { word: "unhealthy", meaning: "不健康的", category: "adj" },
        { word: "hamburger", meaning: "汉堡包", category: "food" },
        { word: "cola", meaning: "可乐", category: "drink" },
        { word: "yesterday", meaning: "昨天", category: "time" },
        { word: "fruit", meaning: "水果", category: "food" },
        { word: "pie", meaning: "馅饼", category: "food" },
        { word: "pizza", meaning: "比萨饼", category: "food" },
        { word: "sandwich", meaning: "三明治", category: "food" },
        { word: "vegetable", meaning: "蔬菜", category: "food" },
        { word: "chicken", meaning: "鸡肉", category: "food" },
        { word: "chocolate", meaning: "巧克力", category: "food" },
        { word: "neighbour", meaning: "邻居", category: "person" },
        { word: "son", meaning: "儿子", category: "family" },
        { word: "daughter", meaning: "女儿", category: "family" },
        { word: "noisy", meaning: "吵闹的", category: "adj" },
        { word: "owl", meaning: "猫头鹰", category: "animal" },
        { word: "dig", meaning: "挖（土），掘（洞）", category: "verb" },
        { word: "make noise", meaning: "制造噪音", category: "phrase" },
        { word: "thousand", meaning: "一千", category: "number" },
        { word: "hundred", meaning: "一百", category: "number" },
        { word: "wild", meaning: "野生环境的，野生的", category: "adj" },
        { word: "south China tiger", meaning: "华南虎", category: "animal" },
        { word: "blue whale", meaning: "蓝鲸", category: "animal" },
        { word: "way", meaning: "路，方式，方法", category: "noun" },
        { word: "die", meaning: "死，死亡", category: "verb" },
        { word: "rhino", meaning: "犀牛", category: "animal" },
        { word: "learn", meaning: "学会，学习", category: "verb" },
        { word: "send", meaning: "安排去，寄，送", category: "verb" },
        { word: "in danger", meaning: "面临危险", category: "phrase" },
        { word: "e-friend", meaning: "网友", category: "person" },
        { word: "country", meaning: "国家", category: "country" },
        { word: "other", meaning: "其他的", category: "adj" },
        { word: "team", meaning: "队", category: "noun" },
        { word: "hobby", meaning: "业余爱好", category: "noun" },
        { word: "grade", meaning: "年级", category: "school" },
        { word: "yourself", meaning: "你自己", category: "pronoun" },
        { word: "shall", meaning: "表示提出或征求意见", category: "verb" },
        { word: "princess", meaning: "公主", category: "person" },
        { word: "police", meaning: "警方，警察部门", category: "job" },
        { word: "exciting", meaning: "令人激动的", category: "adj" },
        { word: "brave", meaning: "勇敢的", category: "adj" },
        { word: "policeman", meaning: "警察", category: "job" },
        { word: "boring", meaning: "没趣的，令人厌倦的", category: "adj" },
        { word: "queen", meaning: "王后", category: "person" },
        { word: "mirror", meaning: "镜子", category: "noun" },
        { word: "fairest", meaning: "最美丽的", category: "adj" },
        { word: "kill", meaning: "杀死", category: "verb" },
        { word: "asleep", meaning: "睡着的", category: "adj" },
        { word: "bee", meaning: "蜜蜂", category: "animal" },
        { word: "insect", meaning: "昆虫", category: "animal" },
        { word: "ant", meaning: "蚂蚁", category: "animal" },
        { word: "anything", meaning: "任何东西", category: "pronoun" },
        { word: "kind", meaning: "种类", category: "noun" },
        { word: "finger", meaning: "手指", category: "body" },
        { word: "dancer", meaning: "跳舞者，舞蹈演员", category: "job" },
        { word: "insect museum", meaning: "昆虫博物馆", category: "place" },
        { word: "model car", meaning: "汽车模型", category: "toy" },
        { word: "science museum", meaning: "科学博物馆", category: "place" },
        { word: "capital", meaning: "首都", category: "place" },
        { word: "north", meaning: "北，北部", category: "direction" },
        { word: "east", meaning: "东，东部", category: "direction" },
        { word: "west", meaning: "西，西部", category: "direction" },
        { word: "south", meaning: "南，南部", category: "direction" },
        { word: "palace", meaning: "王宫，宫殿", category: "place" },
        { word: "most", meaning: "大多数", category: "determiner" },
        { word: "tourist", meaning: "游客", category: "person" },
        { word: "building", meaning: "建筑物，楼房", category: "place" },
        { word: "sushi", meaning: "寿司", category: "food" },
        { word: "air", meaning: "空气", category: "nature" },
        { word: "everywhere", meaning: "处处，到处", category: "adv" },
        { word: "alive", meaning: "活着的", category: "adj" },
        { word: "balloon", meaning: "气球", category: "noun" },
        { word: "factory", meaning: "工厂", category: "place" },
        { word: "smoke", meaning: "烟", category: "noun" },
        { word: "dirty", meaning: "脏的", category: "adj" },
        { word: "clean", meaning: "干净的，洁净的", category: "adj" },
        { word: "hurt", meaning: "感到痛", category: "verb" },
        { word: "fresh", meaning: "清新的", category: "adj" },
        { word: "plant", meaning: "种植", category: "verb" },
        { word: "wood", meaning: "木头，木材", category: "noun" },
        { word: "cool", meaning: "使变凉", category: "verb" },
        { word: "match", meaning: "火柴", category: "noun" },
        { word: "miss", meaning: "想念", category: "verb" },
        { word: "Earth", meaning: "地球", category: "nature" },
        { word: "part", meaning: "地区，区域", category: "noun" },
        { word: "forest", meaning: "森林", category: "nature" },
        { word: "land", meaning: "陆地", category: "nature" },
        { word: "ocean", meaning: "海洋", category: "nature" },
        { word: "rubbish", meaning: "垃圾", category: "noun" },
        { word: "sick", meaning: "生病的", category: "adj" },
        { word: "recycle", meaning: "回收利用，再利用", category: "verb" },
        { word: "own", meaning: "自己的", category: "adj" },
        { word: "plastic", meaning: "塑料", category: "noun" }
    ],

    "6-2": [
        { word: "weigh", meaning: "有……重；重", category: "verb" },
        { word: "kilogram", meaning: "千克；公斤", category: "noun" },
        { word: "centimetre", meaning: "厘米", category: "noun" },
        { word: "taller", meaning: "更高的", category: "adj" },
        { word: "fan", meaning: "迷；爱好者", category: "person" },
        { word: "fantastic", meaning: "极好的", category: "adj" },
        { word: "themselves", meaning: "他们自己、她们自己、它们自己", category: "pronoun" },
        { word: "theatre", meaning: "剧院", category: "place" },
        { word: "go fishing", meaning: "去钓鱼", category: "phrase" },
        { word: "enjoy oneself", meaning: "玩得愉快；得到乐趣", category: "phrase" },
        { word: "get in", meaning: "收割", category: "phrase" },
        { word: "life", meaning: "生活", category: "noun" },
        { word: "writer", meaning: "作家", category: "job" },
        { word: "photographer", meaning: "摄影师", category: "job" },
        { word: "film", meaning: "胶卷", category: "noun" },
        { word: "digital", meaning: "数码的", category: "adj" },
        { word: "street cleaner", meaning: "环卫工人", category: "job" },
        { word: "sweep", meaning: "扫地", category: "verb" },
        { word: "broom", meaning: "扫帚", category: "noun" },
        { word: "drive", meaning: "驾驶", category: "verb" },
        { word: "street sweeper", meaning: "扫地车", category: "vehicle" },
        { word: "wife", meaning: "妻子", category: "family" },
        { word: "poor", meaning: "贫穷的；差的；次的", category: "adj" },
        { word: "fairy", meaning: "仙子；小精灵", category: "person" },
        { word: "wish", meaning: "愿望；祝愿", category: "noun" },
        { word: "by hand", meaning: "用手", category: "phrase" },
        { word: "right away", meaning: "立即；马上", category: "phrase" },
        { word: "in a short time", meaning: "很快", category: "phrase" },
        { word: "carry", meaning: "背；提；拿", category: "verb" },
        { word: "online", meaning: "在线地；在线的", category: "adj" },
        { word: "head teacher", meaning: "校长", category: "job" },
        { word: "PS", meaning: "附言", category: "noun" },
        { word: "mountain", meaning: "山；山脉", category: "nature" },
        { word: "even", meaning: "甚至", category: "adv" },
        { word: "space", meaning: "太空", category: "nature" },
        { word: "dinosaur", meaning: "恐龙", category: "animal" },
        { word: "a piece of", meaning: "一张；一片", category: "phrase" },
        { word: "have a picnic", meaning: "去野餐", category: "phrase" },
        { word: "better and better", meaning: "越来越好", category: "phrase" },
        { word: "oil", meaning: "油", category: "noun" },
        { word: "oil painting", meaning: "油画", category: "noun" },
        { word: "powerful", meaning: "强有力的；力量强大的", category: "adj" },
        { word: "ink", meaning: "墨水；墨汁", category: "noun" },
        { word: "Chinese ink painting", meaning: "中国水墨画", category: "noun" },
        { word: "brush", meaning: "画笔；刷子；刷", category: "noun" },
        { word: "paints", meaning: "绘画颜料", category: "noun" },
        { word: "artist", meaning: "艺术家；画家", category: "job" },
        { word: "unhappy", meaning: "不高兴的", category: "adj" },
        { word: "carefully", meaning: "仔细地", category: "adv" },
        { word: "on the left", meaning: "在左边", category: "phrase" },
        { word: "on the right", meaning: "在右边", category: "phrase" },
        { word: "all the time", meaning: "一直；始终", category: "phrase" },
        { word: "craft", meaning: "手艺", category: "noun" },
        { word: "crown", meaning: "王冠；皇冠", category: "noun" },
        { word: "scissors", meaning: "剪刀", category: "noun" },
        { word: "tape", meaning: "胶带", category: "noun" },
        { word: "glue", meaning: "胶水", category: "noun" },
        { word: "saw", meaning: "锯", category: "noun" },
        { word: "craftman", meaning: "工匠；手艺人", category: "job" },
        { word: "tool", meaning: "工具", category: "noun" },
        { word: "easily", meaning: "容易地", category: "adv" },
        { word: "himself", meaning: "他自己", category: "pronoun" },
        { word: "still", meaning: "仍然", category: "adv" },
        { word: "model house", meaning: "房子模型", category: "toy" },
        { word: "a long time ago", meaning: "很久以前", category: "phrase" },
        { word: "at work", meaning: "忙着（做事情）", category: "phrase" },
        { word: "say to oneself", meaning: "自言自语", category: "phrase" },
        { word: "long race", meaning: "长跑", category: "sport" },
        { word: "short race", meaning: "短跑", category: "sport" },
        { word: "win", meaning: "获胜；赢", category: "verb" },
        { word: "long jump", meaning: "跳远", category: "sport" },
        { word: "high jump", meaning: "跳高", category: "sport" },
        { word: "swimsuit", meaning: "游泳衣", category: "clothes" },
        { word: "swimming cap", meaning: "游泳帽", category: "clothes" },
        { word: "swimming pool", meaning: "游泳池", category: "place" },
        { word: "warm-up", meaning: "准备活动；热身练习", category: "sport" },
        { word: "fit", meaning: "健壮的", category: "adj" },
        { word: "swimming goggles", meaning: "游泳镜", category: "clothes" },
        { word: "bell", meaning: "铃铛", category: "noun" },
        { word: "neck", meaning: "脖子", category: "body" },
        { word: "ago", meaning: "以前", category: "adv" },
        { word: "gatekeeper", meaning: "门卫", category: "job" },
        { word: "praise", meaning: "赞扬；称赞", category: "verb" },
        { word: "praise for", meaning: "因……而表扬……", category: "phrase" },
        { word: "sign", meaning: "标识", category: "noun" },
        { word: "middle", meaning: "中间；中部；中心", category: "noun" },
        { word: "special", meaning: "特别的", category: "adj" },
        { word: "path", meaning: "小路；小径", category: "place" },
        { word: "may", meaning: "可能；可以", category: "verb" },
        { word: "lost", meaning: "迷路的；迷失的", category: "adj" },
        { word: "worry", meaning: "担心", category: "verb" },
        { word: "follow", meaning: "跟随；跟着", category: "verb" },
        { word: "in the middle", meaning: "在中间", category: "phrase" },
        { word: "look out", meaning: "小心；当心", category: "phrase" },
        { word: "no smoking", meaning: "禁止吸烟", category: "sign" },
        { word: "no swimming", meaning: "禁止游泳", category: "sign" },
        { word: "get lost", meaning: "迷路", category: "phrase" },
        { word: "some time", meaning: "一段时间", category: "phrase" },
        { word: "on the way", meaning: "在路上", category: "phrase" },
        { word: "reuse", meaning: "重新利用", category: "verb" },
        { word: "can", meaning: "金属罐", category: "noun" },
        { word: "rubber", meaning: "橡皮", category: "noun" },
        { word: "vase", meaning: "花瓶", category: "noun" },
        { word: "pen holder", meaning: "笔筒", category: "noun" },
        { word: "envelope", meaning: "信封", category: "noun" },
        { word: "plastic", meaning: "塑料制的；塑料的", category: "adj" },
        { word: "rubbish bin", meaning: "垃圾桶", category: "noun" },
        { word: "truck", meaning: "卡车", category: "vehicle" },
        { word: "piece", meaning: "碎片；碎块", category: "noun" },
        { word: "cloth", meaning: "布；布料", category: "noun" },
        { word: "throw away", meaning: "扔掉", category: "phrase" },
        { word: "fairy tale", meaning: "童话（故事）", category: "book" },
        { word: "adult", meaning: "成年人", category: "person" },
        { word: "well-known", meaning: "众所周知的；著名的", category: "adj" },
        { word: "stronger", meaning: "更强大的", category: "adj" },
        { word: "than", meaning: "比", category: "prep" },
        { word: "scarf", meaning: "围巾", category: "clothes" },
        { word: "blow off", meaning: "吹掉", category: "phrase" },
        { word: "take off", meaning: "脱掉", category: "phrase" },
        { word: "Western", meaning: "西方的", category: "adj" },
        { word: "turkey", meaning: "火鸡", category: "animal" },
        { word: "bright", meaning: "明亮的；鲜艳的", category: "adj" },
        { word: "laugh at", meaning: "嘲笑", category: "phrase" },
        { word: "jack-o'-lantern", meaning: "南瓜灯", category: "noun" },
        { word: "pea", meaning: "豌豆", category: "food" },
        { word: "pod", meaning: "豆荚", category: "nature" },
        { word: "forever", meaning: "永远", category: "adv" },
        { word: "bigger", meaning: "更大的", category: "adj" },
        { word: "excited", meaning: "兴奋的", category: "adj" },
        { word: "bullet", meaning: "子弹", category: "noun" },
        { word: "lazy", meaning: "懒惰的", category: "adj" },
        { word: "roof", meaning: "屋顶", category: "noun" },
        { word: "yard", meaning: "院子", category: "place" },
        { word: "hit", meaning: "碰撞；撞击", category: "verb" },
        { word: "see the world", meaning: "见世面", category: "phrase" },
        { word: "one by one", meaning: "一个接一个地", category: "phrase" },
        { word: "look out of", meaning: "往外看", category: "phrase" }
    ]
};

function getAllWords() {
    let allWords = [];
    for (let grade in WORD_DATA) {
        allWords = allWords.concat(WORD_DATA[grade]);
    }
    return allWords;
}

function getWordsByGrade(grade) {
    return WORD_DATA[grade] || [];
}

function getWordsUpToGrade(grade) {
    let allWords = [];
    for (let i = 1; i <= grade; i++) {
        const gradeKey = i.toString();
        if (WORD_DATA[gradeKey]) {
            allWords = allWords.concat(WORD_DATA[gradeKey]);
        }
        for (let semester = 1; semester <= 2; semester++) {
            const semesterKey = gradeKey + "-" + semester;
            if (WORD_DATA[semesterKey]) {
                allWords = allWords.concat(WORD_DATA[semesterKey]);
            }
        }
    }
    return allWords;
}

function getAllGrades() {
    return Object.keys(WORD_DATA);
}

// 浏览器版本不需要 module.exports
// module.exports = { WORD_DATA, getAllWords, getWordsByGrade, getAllGrades };
